~agda --bridges~ is an extension of cubical agda which add parametricity primitives to cubical type theory, as discussed in [[https://lmcs.episciences.org/8651][Cavallo-Harper (CH)]]. The implementation can be found [[https://github.com/antoinevanmuylder/agda/tree/bridges][here]] (bridges branch).

In order to typecheck files of the present library, installing ~agda --bridges~ and the ~cubical~ library is required.

*** Install ghcup (recommended), or just stack
From [[https://www.haskell.org/ghcup/install/][ghcup]]:
#+begin_src shell
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
#+end_src
Follow the ghcup install procedure. Answer yes whenever asked, and ~sudo apt install <...>~ the dependencies required by the script.
After a successful install, restart your terminal
*** Install ~agda --bridges~
#+begin_src shell
stack update # stack comes with ghcup
sudo apt install zlib1g-dev libncurses5-dev gcc #agda prerequisites.
sudo apt install emacs # if you don't have emacs

git clone https://github.com/antoinevanmuylder/agda/ agda-bridges/
cd agda-bridges/
git checkout bridges
cp stack-<version>.yaml stack.yaml # choose version of haskell compiler (tested with ghc 9.4.3)
stack install # builds and copies agda binary to ~/.local/bin/
              # alternatively: `stack install --fast`     (slower agda binary though)
              # `stack install` may take a while to get started
agda-mode compile && agda-mode setup #add hook to emacs init file
#+end_src
Make sure to add ~~/.local/bin/~ to your PATH.
To navigate the the implementation with TAGS, see the end of this file
*** Download the cubical library and register it in =~/.agda/libraries=
The present library (bridgy-lib):
- compiles with ~agda --bridges~ (see instruction above)
- depends on the v0.5 version of the cubical library (which may be master, or a dedicated tag in the future).

To get the latter cubical library to work:
- Clone the appropriate repo: https://github.com/agda/cubical.
- Revert to this commit: ~git checkout 3dc3cd12579544c8~ (28 Apr 2023).
- Once this is done, add the following line to your =~/.agda/libraries= config file:
  #+begin_src shell
  <...>/cubical/cubical.agda-lib # where cubical/ is stored in <...>
  #+end_src
- If you don't have a ~libraries~ file yet, create one. You might have to add ~cubical~ to your defaults. see [[https://agda.readthedocs.io/en/v2.6.2.1/tools/package-system.html][agda lib management]].
*** (Optional) Typecheck the cubical library with the  ~Agda --bridges~ binary
#+begin_src shell
cd <...>/cubical/
stack exec -- make gen-everythings
# then typecheck Cubical.README
#+end_src
*** Use ~Agda --bridges~
Try opening ~Bridgy/Core/BridgePrims.agda~ with emacs, and load with ~C-c C-l~.
other emacs commands:
  https://agda.readthedocs.io/en/v2.6.2.1/tools/emacs-mode.html
*** (Optional) Get rid of warnings in emacs
To get rid of warnings generated by some files of the cubical library:
#+begin_src bash
M-x load-library RET agda2-mode RET
M-x customize-group RET agda2 RET
#+end_src
Then insert the following line (corresponding to the unwanted warning) in the ~Agda2 Program Args~ list:
#+begin_src bash
--warning=no<mywarning>
#+end_src
*** (Optional) Navigate the agda --bridges code base using tags
- Run ~stack install hs-tags~ at the root of the agda bridges repo ~<...>/agda/~.
- Go to ~<...>/agda/mk/paths.mk~ and set the BUILD_DIR variable to be
  #+begin_src shell
  $(TOP)/$(shell stack path --dist-dir)# no space right after the last parenthesis!!
  #+end_src
  Save the file.
- At the root of the agda bridges repo ~<...>/agda/~, type ~stack exec -- make TAGS~. This will generate a TAGS file in ~Agda/src/full/~.
- ~git restore *~.
