In order to typecheck files of this library...
*** Install ~agda --bridges~
~agda --bridges~ is an extension of cubical agda which add parametricity primitives to cubical type theory, as discussed in Cavallo-Harper (CH): https://arxiv.org/pdf/2005.11290.pdf. The implementation can be found here (bridges branch): https://github.com/antoinevanmuylder/agda/tree/bridges.
To install with stack:
#+begin_src shell
git clone https://github.com/antoinevanmuylder/agda/ agda-bridges/
cd agda-bridges/
git checkout bridges
sudo curl -sSL https://get.haskellstack.org/ | sh #if you don't have stack
stack update
cp stack-<version>.yaml stack.yaml # choose version of haskell compiler (e.g. 9.0.2)
sudo apt install zlib1g-dev libncurses5-dev gcc #agda prerequisites.
stack install # builds and copies agda binary to ~/.local/bin/
              # alternatively: `stack install --fast`     (slower agda binary though)
              # `stack install` may take a while to get started
agda-mode compile && agda-mode setup #add hook to emacs init file
#+end_src
To navigate the library with TAGS, see the end of this file
*** Download the cubical library and register it in =~/.agda/libraries=
The present library (bridgy-lib):
- compiles with ~agda --bridges~ (see instruction above)
- depends on the v0.5 version of the cubical library (which may be master, or a dedicated tag in the future).

To get the latter cubical library to work:
- Clone the appropriate repo: https://github.com/agda/cubical.
- Revert to this commit: ~git checkout 3dc3cd12579544c8~ (28 Apr 2023).
- Once this is done, add the following line to your =~/.agda/libraries= config file:
  #+begin_src shell
  <...>/cubical/cubical.agda-lib # where cubical/ is stored in <...>
  #+end_src
- If you don't have a ~libraries~ file yet, create one. You might have to add ~cubical~ to your defaults. see [[https://agda.readthedocs.io/en/v2.6.2.1/tools/package-system.html][agda lib management]].
*** (Optional) Typecheck the cubical library with the  ~Agda --bridges~ binary
#+begin_src shell
cd <...>/cubical/
stack exec -- make gen-everythings
# then typecheck Cubical.README
#+end_src
*** Use ~Agda --bridges~
Try opening ~Bridgy/Core/BridgePrims.agda~ with emacs, and load with ~C-c C-l~.
other emacs commands:
  https://agda.readthedocs.io/en/v2.6.2.1/tools/emacs-mode.html
*** (Optional) Get rid of warnings in emacs
To get rid of warnings generated by some files of the cubical library:
#+begin_src bash
M-x load-library RET agda2-mode RET
M-x customize-group RET agda2 RET
#+end_src
Then insert the following line (corresponding to the unwanted warning) in the ~Agda2 Program Args~ list:
#+begin_src bash
--warning=no<mywarning>
#+end_src
*** (Optional) Navigate the agda --bridges code base using tags
- Run ~stack install hs-tags~ at the root of the agda bridges repo ~<...>/agda/~.
- Go to ~<...>/agda/mk/paths.mk~ and set the BUILD_DIR variable to be
  #+begin_src shell
  $(TOP)/$(shell stack path --dist-dir)# no space right after the last parenthesis!!
  #+end_src
  Save the file.
- At the root of the agda bridges repo ~<...>/agda/~, type ~stack exec -- make TAGS~. This will generate a TAGS file in ~Agda/src/full/~.
- ~git restore *~.
