*** In this repo
Internal parametricity experiments, coded in ~agda --bridges~.
The ~--bridges~ branch can be found here https://github.com/antoinevanmuylder/agda/tree/bridges. It implements the parametricity primitives of Cavallo-Harper (CH) from https://arxiv.org/pdf/2005.11290.pdf. See ~INSTALL.org~ for instructions.
*** Note
To get rid of the ~NoEquivWhenSplitting~ warnings generated by some files of the cubical library:
#+begin_src bash
M-x load-library RET agda2-mode RET
M-x customize-group RET agda2 RET
#+end_src
Then insert the following line in the ~Agda2 Program Args~ list:
#+begin_src bash
--warning=noNoEquivWhenSplitting
#+end_src
*** Quick tour of the files
Check out the ~src/~ directory.
- ~BridgePrims.agda~ contains CH primitives.
- ~BridgeExamples.agda~: basic bridge behaviour + bridge commutation principles
  for ~Bridge, Path, Σ, ×~
- ~ExtentExamples.agda~: commutation with Π
- ~GelExamples.agda~: commutation with the universe ("relativity").
- ~NativeReflGraphRelator.agda~: native reflexive graphs and relators, needed to state parametricity
- ~ParamNativeRelator.agda~: general parametricity theorem
- ~SimpleParam.agda~: proofs of simple Church encodings.
- ~ChurchCircle.agda~: partial proof of the circle Church encoding. On 07/03/2022 we lack
  kan operations for Bridge types to conclude.
- ~SystemF.agda~: shallow embedding of system F where each semantic term is parametric.
