This repo contains internal parametricity experiments, coded in ~agda --bridges~. The ~--bridges~ branch can be found here https://github.com/antoinevanmuylder/agda/tree/bridges. It implements the parametricity primitives of Cavallo-Harper (CH) from https://arxiv.org/pdf/2005.11290.pdf. See ~INSTALL.org~ for instructions.
*** Quick tour of some files
Check out the ~Bridgy/~ directory or ~./Everything.agda~.
- ~Bridgy.Core/~ contains the CH primitives declarations and raw commutation principles (i.e. relational extensionality principles) for important type formers:
  - ~BridgePrims.agda~: declares the CH primitives.
  - ~BridgeExamples.agda~: basic bridge behaviour + commutation principles for ~Bridge~ vs ~Bridge, Path, Σ, ×~.
  - ~ExtentExamples.agda~: commutation ~Bridge~ vs ~Π~.
  - ~GelExamples.agda~: commutation with equivalences, and the universe ("relativity").
  - ~List.adga~: commutation ~Bridge~ vs ~List~.
- ~NRGRelRecord.agda~: native reflexive graphs and relators, needed to state parametricity.
- ~Param.agda~: general parametricity theorem: ~param~.
- ~SimpleParam.agda~: proofs of simple Church encodings with ~param~.
- ~SystemF.agda~: shallow embedding of system F where each semantic term is parametric thanks to ~param~.
*** Comparison with other internally parametric systems
A previous experimental implementation by Cavallo ("ptt") exists [[https://github.com/ecavallo/ptt][here]].
| criterion            | this impl        | ptt impl           |
|----------------------+------------------+--------------------|
| implements           | CH thy           | ≈BCM               |
| on top of            | cubical          | intensional MLTT   |
| arity                | binary           | nary               |
| Gel polarity         | ⊖ (proj, η rule) | ⊕                  |
| can form. relativity | yes              | no?                |
| modelled in          | std. presheaves  | refined presheaves |
